### ISSUE TITLE
isEqualTo is a command, not an operator

### ISSUE THREAD

**Issue by jonpas** [acemod/language-arma-atom#31]
https://github.com/acemod/language-arma-atom/blob/master/grammars/sqf.json#L44

Not really a bug, but I think it's better if `isEqualTo` would be under commands (syntax highlighting) as it makes the code more readable.

**Comment by kymckay** [comment]
It's a comparison operation, no?

**Comment by jonpas** [comment]
Yes it is, but it's still a command rather than normal operator, and not being highlighted makes it harder to read, but that's just my opinion (this is a discussion after-all).

**Comment by kymckay** [comment]
Highlighting is based on whatever theme you're using for that :stuck_out_tongue: This is purely syntax

Mine are highlighted the same as the comparison operators

**Comment by jonpas** [comment]
Yes yes, that's what I meant, same as comparison operators, my bad for confusion.

I simply don't like it being the same, it's probably just me, I still stay behind the argument that it's actually a command though.

**Comment by kymckay** [comment]
I'd be fine with either :smile: Whatever everyone else thinks if fine by me

**Comment by simon84** [comment]
Ist difficult, because in sqf every command is an operator. The language is based on operators and types. Even if, switch, case and else are operators. So it depends on your taste, which operator is coloured as an operator and which as a function or control structure. In sqf there is no difference between these language elements.

**Comment by jonpas** [comment]
Leaving as is.
